### ISSUE TITLE
Get rid off returning only one artifact if name full match request 

### ISSUE THREAD

**Issue by soffokl** [subutai-io/gorjun#117]
We should always return a full list of artifacts and use special arguments if we want to use full name search.

https://cdn.subut.ai:8338/kurjun/rest/template/info?name=apach
https://cdn.subut.ai:8338/kurjun/rest/template/info?name=apache

**Comment by tzununbekov** [comment]
To keep compatibility with Hub and cli, now info endpoint supports `subname` request which will list all substring occurrences, eg: 
https://devcdn.subut.ai:8338/kurjun/rest/template/info?subname=apache
