### ISSUE TITLE
Getting "Signature verification failed" when sending signed file too often

### ISSUE THREAD

**Issue by crioto** [subutai-io/gorjun#118]
I did a manual test of this and found that gorjun starts to authorize normally approximately after one minute of idle.

**Comment by crioto** [comment]
Figured out that this is a cache problem

**Comment by tzununbekov** [comment]
@crioto should work now

**Comment by crioto** [comment]
Thank you, Timur. I will test and report

**Comment by crioto** [comment]
Thanks, guys! Works perfectly!

**Comment by tzununbekov** [comment]
@crioto welcome
