### ISSUE TITLE
Does a CDN Cache Node need to use the actual private key or can it be self-signed?

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/gorjun#133]
In the wiki page for setting up CDN cache nodes [here](https://github.com/subutai-io/gorjun/wiki/Nginx-cache) there's a section on the certificate configuration:

![screen shot 2017-11-11 at 9 44 04 pm](https://user-images.githubusercontent.com/10051386/32690915-7c74b372-c729-11e7-98cd-32ce1dbddd05.png)

Do we need the actual private key of prod, dev, stage or can this be any self-signed key? 

If it has to be the actual key then this has no value for anyone outside of our organization. There's no way we're going to distribute those keys. Is there a workaround for this so everyone can benefit from a cache node?

**Comment by soffokl** [comment]
There is a configuration for Subutai Agent that allows using insecure connections for accessing Kurjun: 
https://github.com/subutai-io/agent/blob/master/config/config.go#L86

**Comment by soffokl** [comment]
On a RH Subutai Agent configuration file located here: `/var/snap/subutai/current/agent.gcfg`

**Comment by akarasulu** [comment]
Thanks again.
