### ISSUE TITLE
Vagrant dev and integration testing environment

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/gorjun#136]
The [PR here](https://github.com/subutai-io/gorjun/pull/135) contains the start of a nice little dev and integration testing environment. It launches a virtual network with multiple virtual machines:

There are a few things that are not done. This epic is to add those missing parts.

**Comment by akarasulu** [comment]
You can also use ansible if you like to provision the environment instead of using embedded shell provisioning blocks like I did. Here's more information on them in case this sounds interesting:

* No changes to your machine but changes virtual machines in env https://www.vagrantup.com/docs/provisioning/ansible_local.html
* Needs changes to your host machine https://www.vagrantup.com/docs/provisioning/ansible.html

Also note that we have several devops scripts already written for Gorjun. Might be worth taking a look at those too.

**Comment by marcoarthur** [comment]
https://github.com/marcoarthur/gorjun-perl-cli/blob/master/lib/Gorjun/Build.pm is specifically suited for building Gorjun and control startup, shutdown, and logging. Helping deploying gorjun for dev environment.
