### ISSUE TITLE
Configure (set up) Gorjun and run it

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/gorjun#138]
Configure Gorjun as it should be running in dev, stage, or production based on a configuration parameter or the current branch. This should be put into the provisioning shell commands to set up the master node.

**Comment by marcoarthur** [comment]
This was achieved with https://github.com/marcoarthur/gorjun-perl-cli/blob/master/lib/Gorjun/Build.pm , we can build gurjun from any commit in history, and also to control startup, shutdown, and logging. But, we need clarification on what parameters we can use it for dev, stage, and master (only branch ?)

**Comment by akarasulu** [comment]
Ok let's integrate this into the gorjun project please. Seems we're going to live with the perl testing scheme.

**Comment by akarasulu** [comment]
@marcoarthur I'm going to close this up but maybe for the next sprint you can create another linked issue to add this integration testing rig to devops and to add coverage metrics. Let's get your tests running on each commit.
