### ISSUE TITLE
Configure NGINX CDN cache nodes against master

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/gorjun#139]
Alter the shell provisioner in the Vagrantfile to set up the caching configuration for the NGINX cache nodes. Make sure to use the branch for dev, prod, stage configurations. All machines should point to the master.

**Comment by akarasulu** [comment]
**NOTE** once the Vagrant file PR is approved it can deploy files into the VM. You might want to put an nginx.conf file with variable parameters which can be changed with sed substitutions.

**Comment by emli** [comment]
How to set up for example 2 cache nodes? I set up only one cache node in my vagrant file. I need DNS.  From which criteria my DNS should select cache node? For example, Route53 select nearest cache node by geolocation.

**Comment by akarasulu** [comment]
I think you are confusing `master` Gorjun instance with the *MASTER* environment here. Still though I cannot understand a damn thing you're saying.
