### ISSUE TITLE
Add option to start up a RH in the environment

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/gorjun#140]
Add an option to startup one or more RH VMs in the internal network to use the cache nodes after populating the master. You might need to populate the master to make this work.

**Comment by akarasulu** [comment]
It might help to test how a RH and subutai import commands will behave. You can include the subutai/stretch-nobridge box in this environment to test it out. You can then see how it all behaves. You can do tests to see how fast thing download after loading the cache.

**Comment by emli** [comment]
![image](https://user-images.githubusercontent.com/5517490/34430983-c8dd7bdc-ec94-11e7-9698-29802cb18045.png)

All templates imported from local cdn.

Can modify /var/snap/subutai/current/agent.gcfg to work with local cdn.

So I close this issue and can assist.

**Comment by emli** [comment]
[Agent]
Debug = true
GpgUser =
AppPrefix = /snap/subutai/current/
LxcPrefix = /var/snap/subutai/common/lxc/
DataPrefix = /var/snap/subutai/current/
GpgPassword = ***

[Management]
Host =
Port = 8443
Secret = secret
GpgUser =
RestPublicKey = /rest/v1/security/keyman/getpublickeyring
Fingerprint =
Allowinsecure = true

[Influxdb]
Server =
Db = metrics
User = root
Pass = root

[CDN]
Allowinsecure = true
URL = 192.168.88.104
SSLport = 8338
Kurjun =

[Template]
Branch =
Version = 6.3.0
Arch = amd64`
