### ISSUE TITLE
Use a REST integration test driver to create and run tests

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/gorjun#142]
There are many libraries and tools out there for testing REST API's. Take a look at what exists. Nice if we can use a swagger specification to drive this. That would mean creating one to describe the existing API. Then we can automate the integration testing with cache nodes etc.

**Comment by marcoarthur** [comment]
I'm closing this issue. Since that we have a Perl driver, that accomplish the same task. https://github.com/marcoarthur/gorjun-perl-cli
