### ISSUE TITLE
Configuration parameter to suppress complaints about bad certificate

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/gorjun#146]
There should be a configuration parameter for the Agent to ignore bad certificates. Work with the agent developers to implement this. That way everyone can use self-signed certificates and local nodes without problems. See also #133

**Comment by soffokl** [comment]
There is a configuration for Subutai Agent that allows using insecure connections for accessing Kurjun:
https://github.com/subutai-io/agent/blob/master/config/config.go#L86

On a RH Subutai Agent configuration file located here: /var/snap/subutai/current/agent.gcfg

**Comment by akarasulu** [comment]
This is great thanks.
