### ISSUE TITLE
Enable CORS on Gorjun web-server

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/gorjun#155]
We need to enable CORS requests to Gorjun for Hub domain, so Hub can upload files to Kurjun directly from Hub web-page.
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by samsonbek** [comment]
CORS should be enabled not only for Hub, but for subutai.io too. On that website it needed to obtain file sizes and display them, in Download section.

**Comment by emli** [comment]
Used settings https://enable-cors.org/server_nginx.html

**Comment by emli** [comment]
https://gist.github.com/alexjs/4165271

**Comment by efeefe** [comment]
This issue is a dependency for [this other one](https://github.com/subutai-io/website/issues/331). Is it done?

**Comment by Dilshat** [comment]
@emli @tilekasankulov guys try this settings instead of the current bloated one 
https://stackoverflow.com/questions/14499320/how-to-properly-setup-nginx-access-control-allow-origin-into-response-header-bas/29113949#29113949
