### ISSUE TITLE
High level diagram of Vagrant dev and integration testing environment

### ISSUE THREAD

**Issue by emli** [subutai-io/gorjun#158]
![dev env](https://user-images.githubusercontent.com/5517490/33280284-c5000340-d3cb-11e7-9eb7-a61d7ec0372d.jpg)

https://github.com/emli/vagrants/blob/master/Vagrantfile

**Comment by akarasulu** [comment]
You could have just drawn this on paper :). Anyways it might be good to show that there can be N cache nodes right? And does the reverse proxy just do uploads to the master?

**Comment by akarasulu** [comment]
When you finish close the issue and make it a wiki page.

**Comment by emli** [comment]
Diagram will improved and verified by admins.

**Comment by emli** [comment]
![image](https://user-images.githubusercontent.com/5517490/33473467-c41e1b10-d6a0-11e7-99fa-f4bf1fe3b13c.png)

**Comment by emli** [comment]
![dev env](https://user-images.githubusercontent.com/5517490/33473677-8d4414a4-d6a1-11e7-9c2f-b14247c76583.jpg)

**Comment by emli** [comment]
![dev env 1](https://user-images.githubusercontent.com/5517490/33476764-5ce46f64-d6ad-11e7-8d7a-7a53ea6b4115.jpg)

**Comment by etursunbaev** [comment]
@emli pls, edit parameter of directive "worker_processes" in nginx.conf
--
Set "2" or "auto"

Not sure it would help on your issues. But worker processes of NGINX should be equal to core numbers.
Will provide additional directives after reviewing NGINX manual and our configuration files.
