### ISSUE TITLE
Integrate testing client and create test data 

### ISSUE THREAD

**Issue by emli** [subutai-io/gorjun#159]
https://github.com/marcoarthur/gorjun-perl-cli - client for gorjun written.

subutai-io#141 - for this issue is for create or load data for gorjun. Let's create test data with client. In this way client also will be tested.

**Comment by marcoarthur** [comment]
I'm closing this issue, we can't create data for the client. The data passed to the client will be saved in gorjun's database. This database could be used, but we see no real value in using it, since we can have a replica of our original data from our dev's hub.
