### ISSUE TITLE
Would be nice to see 'create date' of uploaded files

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/gorjun#160]
When we look at list of files & templates, if same file was uploaded twice, it's not possible to detect which one is old, which is newer (only by md5 of sha hash, but that's not convenient). So, for such cases 'create date' field will be helpful. Please, add 'create date' to both list and info REST endpoints.

**Comment by emli** [comment]
![image](https://user-images.githubusercontent.com/5517490/33311853-4a4b6e34-d450-11e7-8758-5f1e3f1f9190.png)
