### ISSUE TITLE
Document showing CDN/Gorjun configuration in production, and review, signoff

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/gorjun#161]
The sysadmins need to provide a document explaining the configuration of Gorjun / CDN in a production environment. Provide configurations and review the setup in test Vagrantfile to approve that Gorjun guys have it right.

**Comment by akarasulu** [comment]
There might already be documentation on this.

**Comment by etursunbaev** [comment]
Ok. Will provide information here as comments, than after will move to wiki or other document file.

**Comment by emli** [comment]
Worked with sysadmins and get this diagram https://github.com/subutai-io/gorjun/wiki/High-level-diagram-of-Gorjun-architecture.

Also we have documentations in devops repo
