### ISSUE TITLE
Sign the templates for HUB.

### ISSUE THREAD

**Issue by Shahrizada** [subutai-io/gorjun#166]
List of the templates which needs to be signed:

cassandra14
cassandra16
desktop-mate
desktop-mate01
elasticsearch14
elasticsearch16
hadoop14
hadoop16
mongo14
mongo16
openjre714
openjre716
p2pcollect
p2pcollectcron2
solr14
solr16
storm14
storm16
ubuntu14
zookeeper14
zookeeper16

**Comment by AlinaPenkina** [comment]
Test-template is also borked.

**Comment by amol4anoff** [comment]
On master:
haproxysydyk
mongo
p2pcollect
oozie

**Comment by emli** [comment]
I created env with mongo 
![image](https://user-images.githubusercontent.com/5517490/34767775-2c760aa0-f623-11e7-9c16-b6965a5a806d.png)

**Comment by emli** [comment]
All production templates in the list signed, after qa approves we can close issue and continue master templates problem in this issue https://github.com/subutai-io/gorjun/issues/201
