### ISSUE TITLE
Get quota gives a forbidden response after an upload operation

### ISSUE THREAD

**Issue by marcoarthur** [subutai-io/gorjun#189]
This error appears when narrowing down issue #188 . Constraining upload operations for only one type of file: raw, apt or template. When we force this constraint the upload can complete without errors, but quota gets affected:

<pre>
ok 1 - use Gorjun::Build;
make: Entering directory '/home/itaipu/src/go-libs/src/github.com/marcoarthur/gorjun'
go build -ldflags "-w -s -X main.version=6.2.1-SNAPSHOT:master:5ccbbfd7c4e55fbf55ca332b915b9133766bc3e9" -o gorjun
make: Leaving directory '/home/itaipu/src/go-libs/src/github.com/marcoarthur/gorjun'
ok 2 - Created a gorjun build
# Repository: https://github.com/marcoarthur/gorjun.git
# Commit: HEAD
# Branch: dev
# 
# commit 5ccbbfd7c4e55fbf55ca332b915b9133766bc3e9
# Author: Marco Arthur <arthurpbs@gmail.com>
# Date:   Tue Dec 19 17:26:28 2017 -0200
# 
#     Add entry point to run test from external driver
#     
#     This makes the entry point test case to be run for external
#     integration tests.
# 
# diff --git a/main_test.go b/main_test.go
# new file mode 100644
# index 0000000..11695a2
# --- /dev/null
# +++ b/main_test.go
# @@ -0,0 +1,10 @@
# +package main
# +
# +import (
# +	"testing"
# +)
# +
# +// TestMain - drive external testing coverage
# +func TestMain(t *testing.T) {
# +	runMain()
# +}
ok 3 - use Gorjun;
# Test Data Information: 
# 
# User Name: tester
# User Email: tester@gmail.com
# PGP Key:
# -----BEGIN PGP PUBLIC KEY BLOCK-----
# 
# mQENBFoYPuoBCACtzSfHf1FSVVerB00zx/Zhxlbey87UZ+Q/MC8GSYpzHdS27X26
# C2thj0fmWapCk/k6vQL6hRXvfKoAUr6tWbGsfiXgGU3o1cLxXNI/v6TBv2E5Mvqk
# gPDSxFC+hU9ds0wP0M5SRf7xNl2zlYcgNocxEiLwSx2lnMPwhhy8z5d4AJMGKZfu
# smbeZUf//usLf8nFvdLgM2+JWA48l9CbunxufuPy4c5den81coq1s8TFX+n1Kx+Y
# BtDQ8rmM4jRG/aMUChCqKfjNMGlTRHP5Zq77e++uo7bsdP0ljD4vmEtbqyIpGCaM
# IlKYNP0voTnzsXxvPO7t9qgTNiCCMChIidEpABEBAAG0MlRlc3RlciAod2l0aCBz
# dHVwaWQgcGFzc3BocmFzZSkgPHRlc3RlckBnbWFpbC5jb20+iQFOBBMBCAA4FiEE
# 1PTzXOs4SyWNBLaK//hAyy0hbyQFAloYPuoCGwMFCwkIBwIGFQgJCgsCBBYCAwEC
# HgECF4AACgkQ//hAyy0hbySesgf/XJ+l4vcyunUscG7htX5/uTV/uRcVr/8+coI2
# 92VsV9Sz0QFtC/odLrTO6rdzbl5MZgw//iMec56oLYhhvs6+0KqAA1NtgPeQNxPZ
# D+Szwp5NwP0ReInYFRvIceu86WPOGUBmrkqaDc/YdYAXVuObmvVXq1xUJbv4I073
# wUGbTJJrrB8bdlQBYO8yx2yPDWLB8zN2qjTWTzKiLvgcDvNX7GMSDlj3u4yUUHBz
# lN4lkJHCNzjyNLRzSBB2PFfCTFDajaJd6/oXswYNqs9JiQO2Gyw1YyVGag81G3k3
# zeCbFk79lKWPfDtAyAJaic5LVu64O5OCH1H+SnKD2sJcoSLwpbkBDQRaGD7qAQgA
# 8cT9XlErMQhb/dZpS/m97jjHsM7RFgGNG3n7e6UHrAlt/Wzkv4mvRTA+HdxBywxX
# KRaoDkq1AhmdWLZ8qnouCDvBGDaBKQSwIUrLDZYkBiH1zNAFQBC3yJUBtX0HDJry
# I+2b4/zlMLC+rbCxYdkyY3cQ1FEvkJEzsuWqRnkgAlrTLfZssVKHIbENKAqIc+wG
# YDsftZCN8R+VSi0oO5CzEYMwmaffyYov99PjtTIHxPRKUcs9EM9PVGpzle5Hvb62
# UMttb7Xo2TTDDj7TlECxxtlFTzX75l60zAQ0TYMP9rlxH0Ap1RspDNO0tTVoeAgJ
# x2pSvunpOFug7O/VGQcEhwARAQABiQE2BBgBCAAgFiEE1PTzXOs4SyWNBLaK//hA
# yy0hbyQFAloYPuoCGwwACgkQ//hAyy0hbyRD8gf9G4ACTEJ1WjJ6cDY5bPeY8XMk
# /2XEeiNYvtfQtJQg6034r17jL7080iUtcLaPVe5n7PiuJA7dY4AnmN7k8D3fLtVS
# 17x2+NEof6uGJNOQoGXp0fWrQ+NbxCAyADIU11XWGviF3vQwDzwapArnTJTMaE8w
# pMteledI8PynWigfDlQRUoX5YUxMXDFRpPa6nR+pvTt5210MJWgSCqb992+5GIrn
# n0J/oTbBsJhIXbzwmpDJhoM7I61X3pYlg6HZHRCjjWEUJeE0QR0+jkHzH7zEPa9t
# As75s2Xb4x2h1+Bjv0g8AL1OycXgGMiIlAVwVWE6aVRzt0oBVXQxnZGtD166+w==
# =+loE
# -----END PGP PUBLIC KEY BLOCK-----
# 
ok 4 - Register was done
# Name: tester
# PGP key: -----BEGIN PGP PUBLIC KEY BLOCK-----
# 
# mQENBFoYPuoBCACtzSfHf1FSVVerB00zx/Zhxlbey87UZ+Q/MC8GSYpzHdS27X26
# C2thj0fmWapCk/k6vQL6hRXvfKoAUr6tWbGsfiXgGU3o1cLxXNI/v6TBv2E5Mvqk
# gPDSxFC+hU9ds0wP0M5SRf7xNl2zlYcgNocxEiLwSx2lnMPwhhy8z5d4AJMGKZfu
# smbeZUf//usLf8nFvdLgM2+JWA48l9CbunxufuPy4c5den81coq1s8TFX+n1Kx+Y
# BtDQ8rmM4jRG/aMUChCqKfjNMGlTRHP5Zq77e++uo7bsdP0ljD4vmEtbqyIpGCaM
# IlKYNP0voTnzsXxvPO7t9qgTNiCCMChIidEpABEBAAG0MlRlc3RlciAod2l0aCBz
# dHVwaWQgcGFzc3BocmFzZSkgPHRlc3RlckBnbWFpbC5jb20+iQFOBBMBCAA4FiEE
# 1PTzXOs4SyWNBLaK//hAyy0hbyQFAloYPuoCGwMFCwkIBwIGFQgJCgsCBBYCAwEC
# HgECF4AACgkQ//hAyy0hbySesgf/XJ+l4vcyunUscG7htX5/uTV/uRcVr/8+coI2
# 92VsV9Sz0QFtC/odLrTO6rdzbl5MZgw//iMec56oLYhhvs6+0KqAA1NtgPeQNxPZ
# D+Szwp5NwP0ReInYFRvIceu86WPOGUBmrkqaDc/YdYAXVuObmvVXq1xUJbv4I073
# wUGbTJJrrB8bdlQBYO8yx2yPDWLB8zN2qjTWTzKiLvgcDvNX7GMSDlj3u4yUUHBz
# lN4lkJHCNzjyNLRzSBB2PFfCTFDajaJd6/oXswYNqs9JiQO2Gyw1YyVGag81G3k3
# zeCbFk79lKWPfDtAyAJaic5LVu64O5OCH1H+SnKD2sJcoSLwpbkBDQRaGD7qAQgA
# 8cT9XlErMQhb/dZpS/m97jjHsM7RFgGNG3n7e6UHrAlt/Wzkv4mvRTA+HdxBywxX
# KRaoDkq1AhmdWLZ8qnouCDvBGDaBKQSwIUrLDZYkBiH1zNAFQBC3yJUBtX0HDJry
# I+2b4/zlMLC+rbCxYdkyY3cQ1FEvkJEzsuWqRnkgAlrTLfZssVKHIbENKAqIc+wG
# YDsftZCN8R+VSi0oO5CzEYMwmaffyYov99PjtTIHxPRKUcs9EM9PVGpzle5Hvb62
# UMttb7Xo2TTDDj7TlECxxtlFTzX75l60zAQ0TYMP9rlxH0Ap1RspDNO0tTVoeAgJ
# x2pSvunpOFug7O/VGQcEhwARAQABiQE2BBgBCAAgFiEE1PTzXOs4SyWNBLaK//hA
# yy0hbyQFAloYPuoCGwwACgkQ//hAyy0hbyRD8gf9G4ACTEJ1WjJ6cDY5bPeY8XMk
# /2XEeiNYvtfQtJQg6034r17jL7080iUtcLaPVe5n7PiuJA7dY4AnmN7k8D3fLtVS
# 17x2+NEof6uGJNOQoGXp0fWrQ+NbxCAyADIU11XWGviF3vQwDzwapArnTJTMaE8w
# pMteledI8PynWigfDlQRUoX5YUxMXDFRpPa6nR+pvTt5210MJWgSCqb992+5GIrn
# n0J/oTbBsJhIXbzwmpDJhoM7I61X3pYlg6HZHRCjjWEUJeE0QR0+jkHzH7zEPa9t
# As75s2Xb4x2h1+Bjv0g8AL1OycXgGMiIlAVwVWE6aVRzt0oBVXQxnZGtD166+w==
# =+loE
# -----END PGP PUBLIC KEY BLOCK-----
ok 5 - Get quota value done
# {"left":2146845657,"quota":2147483648,"used":637991}
ok 6 - Token got
# 7884aeb1fe81c9d0da910bab27717aa13a2853fdecf24d46ef9ade8c753eed9f
# template : t/Data/abdysamat-apache-subutai-template_4.0.0_amd64.tar.gz
INFO[2017-12-26 11:30:24] User tester, quota usage +637991             
INFO[2017-12-26 11:30:24] File received: abdysamat-apache-subutai-template_4.0.0_amd64.tar.gz(b17eeb7097cf57edfc6b744fcaa01108) 
INFO[2017-12-26 11:30:24] abdysamat-apache saved to template repo by tester 
ok 7 - template upload done
# 0ffc1b11-3def-4fc0-8df9-cd593d4af7f3
INFO[2017-12-26 11:30:24] File 0ffc1b11-3def-4fc0-8df9-cd593d4af7f3 has been signed by tester 
ok 8 - Sign done
ok 9 - Listing template repository
# [{"id":"0ffc1b11-3def-4fc0-8df9-cd593d4af7f3","hash":{"md5":"b17eeb7097cf57edfc6b744fcaa01108","sha256":"75c36819213e7454d81f86e9af339876f75412ca824a89843354dd9007db7639"},"size":637991,"name":"abdysamat-apache","owner":["tester"],"parent":"apache","version":"4.0.0","filename":"abdysamat-apache-subutai-template_4.0.0_amd64.tar.gz","prefsize":"tiny","signature":{"tester":"-----BEGIN PGP SIGNED MESSAGE-----\nHash: SHA256\n\n0ffc1b11-3def-4fc0-8df9-cd593d4af7f3\n-----BEGIN PGP SIGNATURE-----\n\niQFFBAEBCAAvFiEE1PTzXOs4SyWNBLaK//hAyy0hbyQFAlpCTvARHHRlc3RlckBn\nbWFpbC5jb20ACgkQ//hAyy0hbyRJ5wf+IRQiKSa30Ddv8mm5wyB88L1AHXfOp4my\nM1QWaRHKJRfyrNmyiPGb/v8WvpJO6CFZ2pCMSF94M7cNzRjsfSWiM22GyAJkLdC9\nXrJPXIsjphi8F3BsMlTWC5mt9W+T+oAdiCWB5hCMZSc2IE7tY1B4fg1mGovr3jBE\nN7NBrWm6Bky1PHmPubbZoBG6UpSPLHzkNpM1aFPnwfyfpRQe08ECQtMo/InI5ScE\n/HnlTMM9hBsd5PvHFM9qabOGDlvOFY5i5gn5g9uedCH9X9GBE6IXBGUUX2nxf0z4\nw/pI6sbfcQs51CChsBzM0oh+JcbcJnadN6P1Bgv31JebmdFGjsuSTw==\n=x7wm\n-----END PGP SIGNATURE-----\n"},"architecture":"AMD64"}]
INFO[2017-12-26 11:30:24] Shutting down the server                     
PASS
coverage: 33.3% of statements in github.com/subutai-io/agent/log
ok 10 - Shutting down gorjun server
ok  	github.com/marcoarthur/gorjun	1.613s
Subroutine create_file redefined at t/test.t line 20.
ok 11 - use Gorjun;
# Test Data Information: 
# 
# User Name: tester
# User Email: tester@gmail.com
# PGP Key:
# -----BEGIN PGP PUBLIC KEY BLOCK-----
# 
# mQENBFoYPuoBCACtzSfHf1FSVVerB00zx/Zhxlbey87UZ+Q/MC8GSYpzHdS27X26
# C2thj0fmWapCk/k6vQL6hRXvfKoAUr6tWbGsfiXgGU3o1cLxXNI/v6TBv2E5Mvqk
# gPDSxFC+hU9ds0wP0M5SRf7xNl2zlYcgNocxEiLwSx2lnMPwhhy8z5d4AJMGKZfu
# smbeZUf//usLf8nFvdLgM2+JWA48l9CbunxufuPy4c5den81coq1s8TFX+n1Kx+Y
# BtDQ8rmM4jRG/aMUChCqKfjNMGlTRHP5Zq77e++uo7bsdP0ljD4vmEtbqyIpGCaM
# IlKYNP0voTnzsXxvPO7t9qgTNiCCMChIidEpABEBAAG0MlRlc3RlciAod2l0aCBz
# dHVwaWQgcGFzc3BocmFzZSkgPHRlc3RlckBnbWFpbC5jb20+iQFOBBMBCAA4FiEE
# 1PTzXOs4SyWNBLaK//hAyy0hbyQFAloYPuoCGwMFCwkIBwIGFQgJCgsCBBYCAwEC
# HgECF4AACgkQ//hAyy0hbySesgf/XJ+l4vcyunUscG7htX5/uTV/uRcVr/8+coI2
# 92VsV9Sz0QFtC/odLrTO6rdzbl5MZgw//iMec56oLYhhvs6+0KqAA1NtgPeQNxPZ
# D+Szwp5NwP0ReInYFRvIceu86WPOGUBmrkqaDc/YdYAXVuObmvVXq1xUJbv4I073
# wUGbTJJrrB8bdlQBYO8yx2yPDWLB8zN2qjTWTzKiLvgcDvNX7GMSDlj3u4yUUHBz
# lN4lkJHCNzjyNLRzSBB2PFfCTFDajaJd6/oXswYNqs9JiQO2Gyw1YyVGag81G3k3
# zeCbFk79lKWPfDtAyAJaic5LVu64O5OCH1H+SnKD2sJcoSLwpbkBDQRaGD7qAQgA
# 8cT9XlErMQhb/dZpS/m97jjHsM7RFgGNG3n7e6UHrAlt/Wzkv4mvRTA+HdxBywxX
# KRaoDkq1AhmdWLZ8qnouCDvBGDaBKQSwIUrLDZYkBiH1zNAFQBC3yJUBtX0HDJry
# I+2b4/zlMLC+rbCxYdkyY3cQ1FEvkJEzsuWqRnkgAlrTLfZssVKHIbENKAqIc+wG
# YDsftZCN8R+VSi0oO5CzEYMwmaffyYov99PjtTIHxPRKUcs9EM9PVGpzle5Hvb62
# UMttb7Xo2TTDDj7TlECxxtlFTzX75l60zAQ0TYMP9rlxH0Ap1RspDNO0tTVoeAgJ
# x2pSvunpOFug7O/VGQcEhwARAQABiQE2BBgBCAAgFiEE1PTzXOs4SyWNBLaK//hA
# yy0hbyQFAloYPuoCGwwACgkQ//hAyy0hbyRD8gf9G4ACTEJ1WjJ6cDY5bPeY8XMk
# /2XEeiNYvtfQtJQg6034r17jL7080iUtcLaPVe5n7PiuJA7dY4AnmN7k8D3fLtVS
# 17x2+NEof6uGJNOQoGXp0fWrQ+NbxCAyADIU11XWGviF3vQwDzwapArnTJTMaE8w
# pMteledI8PynWigfDlQRUoX5YUxMXDFRpPa6nR+pvTt5210MJWgSCqb992+5GIrn
# n0J/oTbBsJhIXbzwmpDJhoM7I61X3pYlg6HZHRCjjWEUJeE0QR0+jkHzH7zEPa9t
# As75s2Xb4x2h1+Bjv0g8AL1OycXgGMiIlAVwVWE6aVRzt0oBVXQxnZGtD166+w==
# =+loE
# -----END PGP PUBLIC KEY BLOCK-----
# 
ok 12 - Register was done
# Name: tester
# PGP key: -----BEGIN PGP PUBLIC KEY BLOCK-----
# 
# mQENBFoYPuoBCACtzSfHf1FSVVerB00zx/Zhxlbey87UZ+Q/MC8GSYpzHdS27X26
# C2thj0fmWapCk/k6vQL6hRXvfKoAUr6tWbGsfiXgGU3o1cLxXNI/v6TBv2E5Mvqk
# gPDSxFC+hU9ds0wP0M5SRf7xNl2zlYcgNocxEiLwSx2lnMPwhhy8z5d4AJMGKZfu
# smbeZUf//usLf8nFvdLgM2+JWA48l9CbunxufuPy4c5den81coq1s8TFX+n1Kx+Y
# BtDQ8rmM4jRG/aMUChCqKfjNMGlTRHP5Zq77e++uo7bsdP0ljD4vmEtbqyIpGCaM
# IlKYNP0voTnzsXxvPO7t9qgTNiCCMChIidEpABEBAAG0MlRlc3RlciAod2l0aCBz
# dHVwaWQgcGFzc3BocmFzZSkgPHRlc3RlckBnbWFpbC5jb20+iQFOBBMBCAA4FiEE
# 1PTzXOs4SyWNBLaK//hAyy0hbyQFAloYPuoCGwMFCwkIBwIGFQgJCgsCBBYCAwEC
# HgECF4AACgkQ//hAyy0hbySesgf/XJ+l4vcyunUscG7htX5/uTV/uRcVr/8+coI2
# 92VsV9Sz0QFtC/odLrTO6rdzbl5MZgw//iMec56oLYhhvs6+0KqAA1NtgPeQNxPZ
# D+Szwp5NwP0ReInYFRvIceu86WPOGUBmrkqaDc/YdYAXVuObmvVXq1xUJbv4I073
# wUGbTJJrrB8bdlQBYO8yx2yPDWLB8zN2qjTWTzKiLvgcDvNX7GMSDlj3u4yUUHBz
# lN4lkJHCNzjyNLRzSBB2PFfCTFDajaJd6/oXswYNqs9JiQO2Gyw1YyVGag81G3k3
# zeCbFk79lKWPfDtAyAJaic5LVu64O5OCH1H+SnKD2sJcoSLwpbkBDQRaGD7qAQgA
# 8cT9XlErMQhb/dZpS/m97jjHsM7RFgGNG3n7e6UHrAlt/Wzkv4mvRTA+HdxBywxX
# KRaoDkq1AhmdWLZ8qnouCDvBGDaBKQSwIUrLDZYkBiH1zNAFQBC3yJUBtX0HDJry
# I+2b4/zlMLC+rbCxYdkyY3cQ1FEvkJEzsuWqRnkgAlrTLfZssVKHIbENKAqIc+wG
# YDsftZCN8R+VSi0oO5CzEYMwmaffyYov99PjtTIHxPRKUcs9EM9PVGpzle5Hvb62
# UMttb7Xo2TTDDj7TlECxxtlFTzX75l60zAQ0TYMP9rlxH0Ap1RspDNO0tTVoeAgJ
# x2pSvunpOFug7O/VGQcEhwARAQABiQE2BBgBCAAgFiEE1PTzXOs4SyWNBLaK//hA
# yy0hbyQFAloYPuoCGwwACgkQ//hAyy0hbyRD8gf9G4ACTEJ1WjJ6cDY5bPeY8XMk
# /2XEeiNYvtfQtJQg6034r17jL7080iUtcLaPVe5n7PiuJA7dY4AnmN7k8D3fLtVS
# 17x2+NEof6uGJNOQoGXp0fWrQ+NbxCAyADIU11XWGviF3vQwDzwapArnTJTMaE8w
# pMteledI8PynWigfDlQRUoX5YUxMXDFRpPa6nR+pvTt5210MJWgSCqb992+5GIrn
# n0J/oTbBsJhIXbzwmpDJhoM7I61X3pYlg6HZHRCjjWEUJeE0QR0+jkHzH7zEPa9t
# As75s2Xb4x2h1+Bjv0g8AL1OycXgGMiIlAVwVWE6aVRzt0oBVXQxnZGtD166+w==
# =+loE
# -----END PGP PUBLIC KEY BLOCK-----
2017/12/26 11:30:34 http: multiple response.WriteHeader calls
ok 13 - Get quota value done
# Forbidden
</pre>

Last line shows response to Get quota operation.

**Comment by emli** [comment]
I can't reproduce this bug. It works for me.

My steps to reproduce
1)Get quota
2)Upload file
3)Get quota

How you reproduce this `2017/12/26 11:30:34 http: multiple response.WriteHeader calls` line?

**Comment by marcoarthur** [comment]
Use the stress test to reproduce

**Comment by emli** [comment]
After this comment https://github.com/subutai-io/gorjun/issues/188#issuecomment-366684005
