### ISSUE TITLE
Download by owner (REST) with token doesn't work

### ISSUE THREAD

**Issue by emli** [subutai-io/gorjun#218]
For example, this URL doesn't work https://sysnetcdn.subut.ai:8338/kurjun/rest/template/jenkins/management-subutai-template_6.3.4-sysnet_amd64.tar.gz?token= 

This works https://sysnetcdn.subut.ai:8338/kurjun/rest/template/jenkins/management-subutai-template_6.3.4-sysnet_amd64.tar.gz

Here https://github.com/subutai-io/gorjun/blob/master/template/template.go#L120 in the first example, the second argument parsed as `management-subutai-template_6.3.4-sysnet_amd64.tar.gz?token=` , so it search file with this name and couldn't find a template with this name.

**Why we need query parameter `token`?**

There 2 types of templates: public and private. So user can't download his **private** template from this rest. That's why we need token parameter to download private template

**Comment by amol4anoff** [comment]
Done.
