### ISSUE TITLE
Adding new pgp key to owner removes old key

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/gorjun#237]
There is a bug when a new key is added to owner on Gorjun. Previous key gets removed which leads to invalid templates due to signature verification failure on template import

**Comment by emli** [comment]
> Previous key gets removed 

I can't reproduce this bug, write test for this cases, but no success.

Also checked all users keys in our cdns, every user has more than zero keys.

**Comment by Dilshat** [comment]
Ok closing for now, until it happens again
