### ISSUE TITLE
Implement private repositories for all artifacts

### ISSUE THREAD

**Issue by soffokl** [subutai-io/gorjun#24]
We need to allow users upload private artifacts, that will be accessible only from their account. 
User should be able to choose private or public scope for his artifacts.
Private artifacts should be accessible only using token.

**Comment by tzununbekov** [comment]
![image](https://cloud.githubusercontent.com/assets/13515865/17481588/c2025f56-5d9f-11e6-80a6-7f0ce5f51dd0.png)

**Comment by tzununbekov** [comment]
Server-side and CLI functionality implemented, Hub assistance required for further steps

**Comment by tzununbekov** [comment]
Merged to production
