### ISSUE TITLE
Replace getting full list of artifacts with some search mechanism with paging. 

### ISSUE THREAD

**Issue by soffokl** [subutai-io/gorjun#28]
Now any user can get full list of artifacts with single public API URI. 
With big number of artifacts it will require much CPU time. 
We need to replace getting full list of templates with search module. If number of results is too big we can use paging for responses.
Public artifacts owned by Subutai can be showed as default value if no request parameters was specified.

**Comment by akarasulu** [comment]
Might also want to add paging parameters with page size limits on output.
