### ISSUE TITLE
Gorjun doesn't respect "owner" GET parameter

### ISSUE THREAD

**Issue by crioto** [subutai-io/gorjun#53]
When I am getting a file from gorjun and specify it's name and owner - it will return file even if owner was not correct:
```
https://eu0.cdn.subut.ai:8338/kurjun/rest/raw/get?id=<ID>&owner=<SOME_RANDOM_USER>
https://eu0.cdn.subut.ai:8338/kurjun/rest/raw/get?name=<NAME>&owner=<SOME_RANDOM_USER>
```
This doesn't happens when I use the following form:
```
https://eu0.cdn.subut.ai:8338/kurjun/rest/raw/<SOME_RANDOM_USER>/<NAME>
```

**Comment by soffokl** [comment]
After investigation we decided to leave only single way for downloading file:
```
https://cdn.subut.ai:8338/kurjun/rest/raw/<USER>/<FILENAME>
```

Other method with specifying `owner` as argument is excess and will be removed.
