### ISSUE TITLE
Kurjun service should provide tags for templates and filtering by it. 

### ISSUE THREAD

**Issue by soffokl** [subutai-io/gorjun#74]
We can add custom tags to the LXC configuration file like this: 

`subutai.tags = bigdata, apache, database`

Kurjun should expose this information as JSON array and support filtering by this tags.

**Comment by Dilshat** [comment]
This can be done separate via REST API . Thus we can add tags not only to templates but also to any artifact
RESTAPI should allow to add arbitrary tags in form of key-value pairs:
**subutai.category -> bigdata**
**user.tag -> blablabla**

**Comment by soffokl** [comment]
@Dilshat We should define where to store tags. 
If we are storing it in template configuration, we can't change it on Kurjun, because it will require change template archive, hash will be different, signature broken.
If we are storing it only in Kurjun we will not be able to keep this information separately from Kurjun.

**Comment by Dilshat** [comment]
For current needs we need this information on Kurjun only

**Comment by soffokl** [comment]
https://github.com/subutai-io/gorjun/wiki/v1#kurjunresttemplatetag
