### ISSUE TITLE
We need to implement continuous deployment for Krujun server. 

### ISSUE THREAD

**Issue by soffokl** [subutai-io/gorjun#75]
Kurjun server for all 3 environment should be updated after each commit to particular branch.

- dev branch should be deployed to the devcdn.subut.ai;
- master branch should be deployed to the mastercdn.subut.ai;
- latest release version should be deployed to the cdn.subut.ai.

**Comment by p1gmale0n** [comment]
> Marat Bediev
> it will be good, if i can calculate version on build stage,
> and after deploy, builder will check calculated version with version returned from cdn node
> 
> Timur Zununbekov
> build short commit id into binary using makefile and then print it on some rest endpoint?
> 
> Marat Bediev
> for builder it will be enough

**Comment by p1gmale0n** [comment]
added post-deploy version check
