### ISSUE TITLE
Add option to create tokens with long TTL

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/gorjun#92]
For usage of Kurjun by clients we need to be able to supply either permanent or long lived tokens that are precreated by user and managed via Hub UI.
Analogous to amazon keys that are used by automated tools.

**Comment by soffokl** [comment]
Why clients can't authorize and just use tokens?

**Comment by Dilshat** [comment]
because clients will be used by automated tools whereas authorization with Kurjun requires interaction with browser plugin by user.

**Comment by soffokl** [comment]
Authorization with Kurjun does not requires browser plugin, it's use just gpg message signing.

**Comment by Dilshat** [comment]
As i know we have these steps to obtain kurjun token:
1) obtain Kurjun auth id by fingerprint
2) sign it with GPG key
3) obtain Kurjun token by fingerprint and signed auth id

**Comment by soffokl** [comment]
It's correct, but not by fingerprint, it's username.

**Comment by Dilshat** [comment]
yeah in SS we pass fingerprint of user.
So as you see we need to use browser plugin to sign

**Comment by soffokl** [comment]
No. You can do it without browser plugin.

**Comment by Dilshat** [comment]
For this we need to export private key and put it to use by automated tool which might be residing not on a user's laptop, but on a server. This is a security threat.

**Comment by soffokl** [comment]
We have an issue that will allow users to bind several GPG keys to the single account. 
https://github.com/subutai-io/gorjun/issues/30
It is ready and will be merged after the next release.

**Comment by Dilshat** [comment]
Ok, we need to implement accompanying functionality in Hub UI in parallel @absidish
