### ISSUE TITLE
Add ability to update token TTL

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/gorjun#94]
Now we have mechanism where token is obtained once by clients and supplied to env creation workflow.
This workflow uses token in 2 steps: import templates and clone containers.
Import template can take significant amount of time base on connection speed.
Thus, token might get expired till the workflow reaches the clone containers step.
We need to be able to periodically refresh a token somehow so that its TTL is prolonged.

**Comment by soffokl** [comment]
@Dilshat Adding ability to update token TTL looks insecure a bit. 
Importing template with token and cloning container are two different operation, that can be executed separately. 
It's looks like a better way just use different tokens for each operation if you wary about token expiration.

**Comment by Dilshat** [comment]
The problem is we ask user for token only once in the very beginning of environment creation, then user "goes to sit on a coach" until all is done. What you offer requires another interaction with user.
May be we can do this: when template import is done, Kurjun itself updates the token used for import so that it has more time for cloning. This way we don't allow user to update the token, rather we have Kurjun itself do this.

**Comment by soffokl** [comment]
@Dilshat When the import of template is done - token is not required for clone.

**Comment by Dilshat** [comment]
what is **-k** switch for then in clone command, @soffokl ?

**Comment by soffokl** [comment]
Clone binding supports cloning from templates that was not imported to the RH previously. 
If template not found locally it executes import binding to install required template. 
**-k** switch is a token for importing template before clone, but it works only if template was not installed before.

**Comment by Dilshat** [comment]
Closing this issue. See https://github.com/subutai-io/base/issues/1881

**Comment by Dilshat** [comment]
Since **clone** binding can not clone private template by ID without token, this issue is still actual

**Comment by soffokl** [comment]
@Dilshat Create issue about cloning container by ID without token instead of this.
